//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace NikolaVan.lib.Models.UmbracoCmsContent
{
	/// <summary>BlogAuthor</summary>
	[PublishedModel("blogAuthor")]
	public partial class BlogAuthor : PublishedContentModel, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new const string ModelTypeAlias = "blogAuthor";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogAuthor, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public BlogAuthor(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// AuthorDescription
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("authorDescription")]
		public global::System.Web.IHtmlString AuthorDescription => this.Value<global::System.Web.IHtmlString>("authorDescription");

		///<summary>
		/// AuthorImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("authorImage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent AuthorImage => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("authorImage");

		///<summary>
		/// Menu Title: Názov stránky pre menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("menuTitle")]
		public string MenuTitle => global::NikolaVan.lib.Models.UmbracoCmsContent.SEO.GetMenuTitle(this);

		///<summary>
		/// Meta Description: Popis stránky
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => global::NikolaVan.lib.Models.UmbracoCmsContent.SEO.GetMetaDescription(this);

		///<summary>
		/// Page Title: Názov stránky
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("pageTitle")]
		public string PageTitle => global::NikolaVan.lib.Models.UmbracoCmsContent.SEO.GetPageTitle(this);

		///<summary>
		/// UmbracoNaviHide: Ak je táto voľba zaškrtnutá, potom daná stránka nebude súčasťou menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide => global::NikolaVan.lib.Models.UmbracoCmsContent.SEO.GetUmbracoNaviHide(this);
	}
}
