//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace NikolaVan.lib.Models.UmbracoCmsContent
{
	/// <summary>Blog Article</summary>
	[PublishedModel("blogArticle")]
	public partial class BlogArticle : PublishedContentModel, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new const string ModelTypeAlias = "blogArticle";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogArticle, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public BlogArticle(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// ArticleAuthor
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("articleAuthor")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent ArticleAuthor => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("articleAuthor");

		///<summary>
		/// ArticleCategories
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("articleCategories")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent> ArticleCategories => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>>("articleCategories");

		///<summary>
		/// ArticleContent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("articleContent")]
		public global::Newtonsoft.Json.Linq.JToken ArticleContent => this.Value<global::Newtonsoft.Json.Linq.JToken>("articleContent");

		///<summary>
		/// ArticlePreviewImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("articlePreviewImage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent ArticlePreviewImage => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("articlePreviewImage");

		///<summary>
		/// ArticlePreviewText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("articlePreviewText")]
		public string ArticlePreviewText => this.Value<string>("articlePreviewText");

		///<summary>
		/// Menu Title: Názov stránky pre menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("menuTitle")]
		public string MenuTitle => global::NikolaVan.lib.Models.UmbracoCmsContent.SEO.GetMenuTitle(this);

		///<summary>
		/// Meta Description: Popis stránky
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => global::NikolaVan.lib.Models.UmbracoCmsContent.SEO.GetMetaDescription(this);

		///<summary>
		/// Page Title: Názov stránky
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("pageTitle")]
		public string PageTitle => global::NikolaVan.lib.Models.UmbracoCmsContent.SEO.GetPageTitle(this);

		///<summary>
		/// UmbracoNaviHide: Ak je táto voľba zaškrtnutá, potom daná stránka nebude súčasťou menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.3")]
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide => global::NikolaVan.lib.Models.UmbracoCmsContent.SEO.GetUmbracoNaviHide(this);
	}
}
